# Generated by Django 3.0.7 on 2021-02-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Buy',
        ),
        migrations.AlterModelOptions(
            name='buy',
            options={'verbose_name': 'buy', 'verbose_name_plural': 'buy'},
        ),
    ]
