# Generated by Django 3.0.7 on 2021-02-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210208_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
